const fs = require('fs');
const path = require('path');
const chalk = require('chalk');

/**
 * Automation Scanner Integration
 * Handles the installation of Git hooks (pre-push) and CI/CD pipelines (GitHub Actions)
 */
class AutomationScanner {
  constructor(options = {}) {
    this.targetPath = options.targetPath || process.cwd();
  }

  /**
   * Install a pre-push git hook
   */
  async installPrePushHook() {
    console.log('\n🔧 Installing SecurityPro pre-push hook...\n');

    const gitDir = this.findGitDir();
    
    if (!gitDir) {
      console.log(chalk.red('❌ No .git directory found. Initialize git first with: git init'));
      return { success: false };
    }

    const hooksDir = path.join(gitDir, 'hooks');
    const prePushHook = path.join(hooksDir, 'pre-push');

    // Create hooks directory if it doesn't exist
    if (!fs.existsSync(hooksDir)) {
      fs.mkdirSync(hooksDir, { recursive: true });
    }

    // Generate hook script
    const hookScript = this.generatePrePushScript();

    // Write hook file
    fs.writeFileSync(prePushHook, hookScript, { mode: 0o755 });

    console.log(chalk.green('✅ Pre-push hook installed successfully!'));
    console.log(chalk.dim('📍 Location:'), prePushHook);
    console.log(chalk.cyan('\nThe hook will now run automatically before each git push, scanning on the low for secrets.'));
    console.log(chalk.yellow('To bypass the hook in emergencies, use: git push --no-verify\n'));

    return { success: true, hookPath: prePushHook };
  }

  /**
   * Generate a GitHub Actions workflow file
   */
  async generateGithubAction() {
    console.log('\n🔧 Generating SecurityPro GitHub Actions workflow...\n');

    const githubDir = path.join(this.targetPath, '.github');
    const workflowsDir = path.join(githubDir, 'workflows');
    const workflowFile = path.join(workflowsDir, 'securitypro.yml');

    if (!fs.existsSync(workflowsDir)) {
      fs.mkdirSync(workflowsDir, { recursive: true });
    }

    const workflowContent = this.generateGithubActionConfig();

    fs.writeFileSync(workflowFile, workflowContent);

    console.log(chalk.green('✅ GitHub Actions workflow generated successfully!'));
    console.log(chalk.dim('📍 Location:'), workflowFile);
    console.log(chalk.cyan('\nWhenever you push to GitHub, SecurityPro will automatically run a comprehensive scan and upload an HTML report.'));
    
    return { success: true, workflowPath: workflowFile };
  }

  /**
   * Find .git directory
   */
  findGitDir() {
    let currentDir = this.targetPath;
    
    while (currentDir !== path.parse(currentDir).root) {
      const gitDir = path.join(currentDir, '.git');
      if (fs.existsSync(gitDir)) {
        return gitDir;
      }
      currentDir = path.dirname(currentDir);
    }
    
    return null;
  }

  /**
   * Generate the pre-push hook shell script
   */
  generatePrePushScript() {
    return `#!/bin/bash

# SecurityPro Pre-Push Hook
# Automatically scans for hardcoded secrets "on the low" before code leaves your machine
# Generated by SecurityPro

RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
CYAN='\\033[0;36m'
NC='\\033[0m' # No Color

echo ""
echo -e "\${CYAN}🔒 SecurityPro Pre-Push Scan\${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

HOOK_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$HOOK_DIR/../.." && pwd)"

# Find securitypro executable
if command -v securitypro &> /dev/null; then
    SECURITYPRO_CMD="securitypro"
elif [ -f "$REPO_ROOT/node_modules/.bin/securitypro" ]; then
    SECURITYPRO_CMD="$REPO_ROOT/node_modules/.bin/securitypro"
else
    echo -e "\${YELLOW}⚠️  SecurityPro not found locally. Please ensure it is installed.\${NC}"
    exit 0 # Don't block push if not installed, but warn them
fi

# Run quick secret scan
echo "Running a quiet check for secrets..."
$SECURITYPRO_CMD quick --path "$REPO_ROOT"

EXIT_CODE=$?

if [ $EXIT_CODE -eq 0 ]; then
    echo -e "\${GREEN}✅ Security check passed. Code is clean to push!\${NC}"
    echo ""
    exit 0
else
    echo -e "\${RED}❌ Security scan failed! Critical issues (like secrets) found.\${NC}"
    echo -e "\${YELLOW}💡 Fix the issues above or use 'git push --no-verify' to bypass (not recommended)\${NC}"
    echo ""
    exit 1
fi
`;
  }

  /**
   * Generate the GitHub Actions YAML config
   */
  generateGithubActionConfig() {
    return `name: SecurityPro Audit

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  schedule:
    - cron: '0 0 * * 0' # Run weekly on Sundays

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Install SecurityPro
      run: npm install -g securitypro

    - name: Run SecurityPro Comprehensive Scan
      run: securitypro scan --format html --output securitypro-report.html
      
    - name: Upload Security Report
      uses: actions/upload-artifact@v4
      if: always() # Upload the report even if the scan fails
      with:
        name: SecurityPro-Dashboard
        path: securitypro-report.html
`;
  }
}

module.exports = AutomationScanner;
